#!/bin/bash
# DO NOT EDIT THIS FILE

TARGETS="pokemon.cmo player.cmo command.cmo \
  testCommand.cmo author.cmo test.cmo" \

OCAMLBUILD="ocamlbuild -use-ocamlfind"

$OCAMLBUILD $TARGETS
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING

Oh no! Your code currently does not compile ;(   
Check the error messages above carefully to determine what 
is wrong. See a consultant for help if you cannot determine
what is wrong.
===========================================================
EOF
  exit 1
fi

if ocamlbuild -use-ocamlfind checktypes.cmo ; then
  cat <<EOF
===========================================================
Yay! Your function names and types look good to me :D
Congratulations!
===========================================================
EOF
else
  cat <<EOF
===========================================================
WARNING

Oh no! Your function names and types look broken to me ;(
Please fix your names and types.  Check the error messages
above carefully to determine what is wrong.  See a 
consultant for help if you cannot determine what is wrong.
===========================================================
EOF
fi

